# Maintainer: Alex Lay-Calvert
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=l1t-bin
pkgver=0.1.1
pkgrel=1
pkgdesc="A terminal strategy game about shooting lasers and lighting statues"
url="https://github.com/alex-laycalvert/l1t"
license=("GPLv3")
arch=("x86_64")
provides=("l1t")
conflicts=("l1t")
source=("https://github.com/alex-laycalvert/l1t/releases/download/v$pkgver/l1t-$pkgver-x86_64.tar.gz")
sha256sums=("4488d379a214df855f9e9743571984cca193878d2be364be23d705809b426a3d")

package() {
    install -Dm755 l1t -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
