# Maintainer: Alex Lay-Calvert
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=l1t-bin
pkgver=0.1.1
pkgrel=1
pkgdesc="A terminal strategy game about shooting lasers and lighting statues"
url="https://github.com/alex-laycalvert/l1t"
license=("GPLv3")
arch=("x86_64")
provides=("l1t")
conflicts=("l1t")
source=("https://github.com/alex-laycalvert/l1t/releases/download/v$pkgver/l1t-$pkgver-x86_64.tar.gz")
sha256sums=("d7f561a1ca11b74c8b3c29e950af0af7f31c0689cdf3419f376ebbf04ff7ede7")

package() {
    install -Dm755 l1t -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
